spring:
  application:
    name: calendarApp

  datasource:
    url: jdbc:sqlite:task_scheduler.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: com.calendarApp.calendarApp.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  config: classpath:logback-spring.xml  # Esta línea es opcional si el archivo está en src/main/resources
  level:
    root: INFO
    org.springframework.security: INFO
    com.calendarApp: INFO
  pattern:
    console: "[%d{HH:mm:ss}] [%-5level] [%logger{36}] - %msg%n"

server:
  port: 8080
